#!/bin/bash

usage(){
    local code=$1
    [ -z "$code" ] && code=0
    cat <<EOH
Usage:
    git changelog [<previous-tag>] [<current-tag>]
EOH
    exit ${code}
}

current=HEAD
case $# in
    2)
        previous=$1
        current=$2
        ;;
    1)
        previous=$1
        ;;
    0)
        previous=$(git describe --tag --abbrev=0)
        ;;
esac

git fetch --all --tags >&2
git status -uno -s >&2
git log --oneline --reverse --no-decorate ${previous}..${current}
