#!/bin/bash
#
# Enhancement to the original git branch command
# Add the remote name to the classic branch list
#
filter=$1

_is_current_branch(){
    local line=${1}
    return [ '*' = "$(echo "${line}" | awk '{ print $1; }')" ]
}

_get_branch_remote(){
    local branch=${1}
    git config -l | grep "branch.${branch}.remote" | awk -F "=" '{ print $2; }'
}

git branch | while read b
do
    end="\033[00m"
    if [ '*' = "$(echo "$b" | awk '{ print $1; }')" ]
    then
        beg="\033[01m"
    else
        beg=${end}
    fi
    branch=$(echo "$b" | awk '{ print $NF; }')
    remote=$(git config -l | grep "branch.${branch}.remote" | awk -F "=" '{ print $2; }')
    [ -n "${filter}" -a "${remote}" != "${filter}" ] || printf "${beg}%-10s %s${end}\n" "[${remote:-<none>}]" "$branch"
done
