#!/bin/bash

_echo(){
    echo -e "\033[01;33m${1}\033[00m"
}

t=$(date --iso-8601=seconds --date="${1:-now}")

_echo "Last commit was: \n"
git log -1 --no-decorate
_echo "\nDate will be amended to: ${t/T/ } - Confirm ? (y/N)"
read r
[ "${r}" = "y" ] && env GIT_COMMITTER_DATE=${t} git commit --amend --date=${t}
