#!/bin/bash
#
# Give the current branch name
#

_usage(){
    local code=${1:-0}
    echo "Usage: git current-branch"
    exit ${code}
}

case ${1} in
    -h|--help|--usage)
        _usage
        ;;
esac

git branch | awk '($1 == "*") { print $2; }'
